export enum ItemTypes {
  AMMO = "ammo",
  AMMO_BOX = "ammoBox",
  ANY = "any",
  ARMOR = "armor",
  ARMOR_PLATE = "armorPlate",
  BACKPACK = "backpack",
  BARTER = "barter",
  CONTAINER = "container",
  GLASSES = "glasses",
  GRENADE = "grenade",
  GUN = "gun",
  HEADPHONES = "headphones",
  HELMET = "helmet",
  INJECTORS = "injectors",
  KEYS = "keys",
  MARKED_ONLY = "markedOnly",
  MEDS = "meds",
  MODS = "mods",
  NO_FLEA = "noFlea",
  PISTOL_GRIP = "pistolGrip",
  PRESET = "preset",
  PROVISIONS = "provisions",
  RIG = "rig",
  SUPPRESSOR = "suppressor",
  WEARABLE = "wearable",
}
